/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosafe.installpages;

import sosafe.installpages.InstallFireS;
import java.awt.Color;
import java.awt.GridLayout;
import javafx.scene.control.TableColumn;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableModel;
import sosafe.Admin;
import sosafe.Room;

/**
 *
 * @author yuxia
 */
public class InstallMotionS extends javax.swing.JFrame {
    Admin admin;
    Room[][] rooms;
    /**
     * Creates new form InstallMotionS
     */
    public InstallMotionS(Admin ad) {
        super("Installation of MOTION Sensors");
        admin = ad;
        int numFloor = admin.getNumOfFloor();
        int roomsPerStory = admin.getNumRoomPerStory();
        System.out.println(numFloor + ", " + roomsPerStory);
        GridLayout ayout = new GridLayout(5,5);
        //new GridLayout(numFloor, roomsPerStory)
        //roomDisplayPanel.setLayout(new GridLayout(5, 5));
        
        /*for (int i = 0; i < numFloor; i++){
            for (int j = 0; j < roomsPerStory; i++){
                JLabel curRoom = new JLabel();
                curRoom.setBackground(Color.blue);
                roomDisplayPanel.add(curRoom);
            }
        }*/
//        Color color = Color.BLACK;
//        MatteBorder border = new MatteBorder(1, 1, 1, 1, color);
//        displayTable.setBorder(border);
        initComponents();
        this.setLocationRelativeTo(null);
        //displayTable.setRowHeight(50); or try to fill the panel
        DefaultTableModel model;
            model = (DefaultTableModel) displayTable.getModel();
            model.setRowCount(0);
        //displayTable.addColumn("");
        //5-> 1 because table addrow to bottom
        for (int i = 5; i >= 1; i--){
            String floor = "Floor " + i;
            model.addRow(new Object[]{floor, false, false, false, false, false});
        }
        displayTable.setShowGrid(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        roomDisplayPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        instructionLabel.setText("Select the Rooms to install Motion Sensors");

        confirmButton.setText("Next");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        displayTable.setBackground(new java.awt.Color(0, 255, 255));
        displayTable.setBorder(new javax.swing.border.MatteBorder(null));
        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Building", "Room 1", "Room 2", "Room 3", "Room 4", "Room 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        displayTable.setIntercellSpacing(new java.awt.Dimension(10, 10));
        displayTable.setRowHeight(50);
        displayTable.setRowSelectionAllowed(false);
        displayTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(displayTable);

        javax.swing.GroupLayout roomDisplayPanelLayout = new javax.swing.GroupLayout(roomDisplayPanel);
        roomDisplayPanel.setLayout(roomDisplayPanelLayout);
        roomDisplayPanelLayout.setHorizontalGroup(
            roomDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomDisplayPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        roomDisplayPanelLayout.setVerticalGroup(
            roomDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomDisplayPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roomDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instructionLabel)
                    .addComponent(confirmButton))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        Room[][] rooms = admin.getRooms();
        for (int i = 0; i < 5; i++){
            for (int j = 1; j < 6; j++){
                if ((Boolean)displayTable.getValueAt(i, j)){                 
                    System.out.println("Floor " + (5 - i) + ", Room " + j + "selected for Motion Sensor");                   
                    rooms[5-i-1][j-1].installMotionSensor();
                }
            }
        }
        
        //kill current page, go to next page
        JOptionPane.showMessageDialog(this, "Motion Sensors Implemented!");
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstallFireS(admin).setVisible(true);
                //new InstallFireS(admin).setVisible(true);
            }
        });
        
        
        
        
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstallMotionS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstallMotionS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstallMotionS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstallMotionS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new InstallMotionS(new Admin(5, 5));
                frame.setVisible(true);
                frame.setTitle("Installation of MOTION Sensors");
                //new InstallMotionS(new Admin(5, 5)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JTable displayTable;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel roomDisplayPanel;
    // End of variables declaration//GEN-END:variables
}
